### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by KirillDogadin-std** [KirillDogadin-std/Lab-Semantic#1]
Description
---
running the repo via 

```bash
 bash run.sh -m ITC -d ../../dataset_lab/BootEA_DBP_WD_100K/
```

gives an error

```
Traceback (most recent call last):
  File "run_ITC.py", line 17, in <module>
    data = DataModel(args)
  File "/Lab-Semantic/code/data_model.py", line 75, in __init__
    self._generate_literal_vectors()
  File "/Lab-Semantic/code/data_model.py", line 91, in _generate_literal_vectors
    literal_encoder = LiteralEncoder(self.literal_list, word2vec, self.args)
  File "/Lab-Semantic/code/literal_encoder.py", line 177, in __init__
    encoder_model = AutoEncoderModel(literal_vector_list, self.args)
  File "/Lab-Semantic/code/literal_encoder.py", line 33, in __init__
    self.word_vec_list = np.reshape(word_vec_list, [len(word_vec_list), input_dimension])
  File "<__array_function__ internals>", line 6, in reshape
  File "/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 55, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 44, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
  File "/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError: Unable to allocate 5.26 GiB for an array with shape (942199, 5, 300) and data type float32
```

Request
---
- In case you've already launched the code and resolved the problem, please describe what should be done.
- In case you've descided to test on another dataset (smaller one), please share it.
- In case you didnt test the set up yet, please run the code and see if the decsribed scenario also occures for you. Also, please report your finding here.

**Comment by KirillDogadin-std** [comment]
manual discussion over other accessible results into 
 - address supervisor
 - in order to work with data provided initially (by ref or in repo) one will have to use gpu.
